# Generated by Django 5.2.6 on 2025-09-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansatt',
            fields=[
                ('ansattnr', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fornavn', models.CharField(max_length=40)),
                ('etternavn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentnr', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fornavn', models.CharField(max_length=40)),
                ('etternavn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Emne',
            fields=[
                ('emnekode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('emnenavn', models.CharField(max_length=40)),
                ('beskrivelse', models.CharField(max_length=100)),
                ('foreleser', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, to='app2000.ansatt')),
            ],
        ),
        migrations.CreateModel(
            name='Forelesning',
            fields=[
                ('pk', models.CompositePrimaryKey('dato', 'emnekode', 'student', blank=True, editable=False, primary_key=True, serialize=False)),
                ('dato', models.DateField()),
                ('innhold', models.CharField(max_length=100)),
                ('emnekode', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, to='app2000.emne')),
                ('student', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, to='app2000.student')),
            ],
        ),
    ]
