# Generated by Django 5.2.6 on 2025-09-11 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansatt',
            fields=[
                ('ansattnr', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fornavn', models.CharField(max_length=40)),
                ('etternavn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Emne',
            fields=[
                ('emnekode', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('emnenavn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentnr', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fornavn', models.CharField(max_length=40)),
                ('etternavn', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Forelesning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.CharField(max_length=100)),
                ('emnekode', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.PROTECT, to='app2000.emne')),
            ],
        ),
        migrations.CreateModel(
            name='Forelesningstime',
            fields=[
                ('pk', models.CompositePrimaryKey('dato', 'forelesningsid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('dato', models.DateField()),
                ('ansattnr', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, to='app2000.ansatt')),
                ('forelesningsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2000.forelesning')),
                ('studentnr', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, to='app2000.student')),
            ],
        ),
        migrations.AddField(
            model_name='forelesning',
            name='foreleser',
            field=models.ManyToManyField(max_length=40, through='app2000.Forelesningstime', to='app2000.ansatt'),
        ),
        migrations.AddField(
            model_name='forelesning',
            name='student',
            field=models.ManyToManyField(max_length=40, through='app2000.Forelesningstime', to='app2000.student'),
        ),
    ]
