# Generated by Django 5.2.6 on 2025-09-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2000', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emne',
            name='emnekode',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forelesning',
            name='emnekode',
            field=models.ForeignKey(max_length=7, on_delete=django.db.models.deletion.PROTECT, to='app2000.emne'),
        ),
    ]
