# Generated by Django 5.2.6 on 2025-09-17 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2000', '0002_alter_emne_emnekode_alter_forelesning_emnekode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEmne',
            fields=[
                ('pk', models.CompositePrimaryKey('emnekode', 'student', blank=True, editable=False, primary_key=True, serialize=False)),
                ('emnekode', models.ForeignKey(max_length=7, on_delete=django.db.models.deletion.PROTECT, to='app2000.emne')),
                ('student', models.ForeignKey(max_length=6, on_delete=django.db.models.deletion.PROTECT, to='app2000.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Forelesning',
        ),
    ]
